import { lazy, Suspense, useEffect, useMemo, useState } from "react";
import { App as AntApp, Avatar, Button, Drawer, Dropdown, Form, Grid, Input, Layout, Menu, Modal, Skeleton, Space, Typography, message } from "antd";
import { AppstoreOutlined, KeyOutlined, ProjectOutlined, LogoutOutlined, MenuFoldOutlined, MenuUnfoldOutlined, SettingOutlined, TeamOutlined, UserOutlined } from "@ant-design/icons";
import { api, authStore } from "./api";
import type { User } from "./types";
const DashboardPage = lazy(() => import("./pages/DashboardPage"));
const ProfilesPage = lazy(() => import("./pages/ProfilesPage"));
const UsersPage = lazy(() => import("./pages/UsersPage"));
const JobsPage = lazy(() => import("./pages/JobsPage"));
const SettingsPage = lazy(() => import("./pages/SettingsPage"));

type PageKey="dashboard"|"profiles"|"users"|"jobs"|"settings";
function SignIn({onLogin}:{onLogin:(user:User)=>void}){
  const[loading,setLoading]=useState(false);
  const submit=async(values:{identity:string;password:string})=>{setLoading(true);try{const result=await api.login(values.identity,values.password);authStore.set(result.token);onLogin(result.user)}catch(e){message.error(e instanceof Error?e.message:"Unable to sign in")}finally{setLoading(false)}};
  return <div className="login-shell"><div className="login-art"><div className="brand-mark large"><ProjectOutlined/></div><Typography.Title>Move every application forward.</Typography.Title><Typography.Paragraph>One workspace for candidate profiles, bidder assignments, job activity, and payouts.</Typography.Paragraph><div className="login-orb one"/><div className="login-orb two"/></div><div className="login-panel"><div className="login-card"><div className="mobile-brand"><div className="brand-mark"><ProjectOutlined/></div><strong>BidFlow</strong></div><Typography.Title level={2}>Welcome back</Typography.Title><Typography.Text type="secondary">Sign in with your email address or user ID.</Typography.Text><Form layout="vertical" size="large" onFinish={submit} requiredMark={false}><Form.Item name="identity" label="Email or user ID" rules={[{required:true}]}><Input autoFocus prefix={<UserOutlined/>} placeholder="Enter email or user ID"/></Form.Item><Form.Item name="password" label="Password" rules={[{required:true}]}><Input.Password placeholder="Enter your password"/></Form.Item><Button htmlType="submit" type="primary" block loading={loading}>Sign in</Button></Form></div></div></div>;
}

function ChangePasswordModal({open,onClose}:{open:boolean;onClose:()=>void}){
  const[form]=Form.useForm();const[saving,setSaving]=useState(false);
  const submit=async()=>{try{const values=await form.validateFields();setSaving(true);await api.changePassword(values.current_password,values.new_password);message.success("Password changed successfully");form.resetFields();onClose()}catch(error){if(error instanceof Error)message.error(error.message)}finally{setSaving(false)}};
  return <Modal open={open} title="Change password" okText="Change password" confirmLoading={saving} onOk={submit} onCancel={()=>{form.resetFields();onClose()}} destroyOnHidden><Form form={form} layout="vertical" requiredMark={false}><Form.Item name="current_password" label="Current password" rules={[{required:true,message:"Enter your current password"}]}><Input.Password autoComplete="current-password" placeholder="Current password"/></Form.Item><Form.Item name="new_password" label="New password" rules={[{required:true,min:8,message:"Use at least 8 characters"}]}><Input.Password autoComplete="new-password" placeholder="At least 8 characters"/></Form.Item><Form.Item name="confirm_password" label="Confirm new password" dependencies={["new_password"]} rules={[{required:true,message:"Confirm your new password"},({getFieldValue})=>({validator(_,value){return !value||getFieldValue("new_password")===value?Promise.resolve():Promise.reject(new Error("Passwords do not match"))}})]}><Input.Password autoComplete="new-password" placeholder="Repeat new password"/></Form.Item></Form></Modal>;
}

function Workspace({user,onLogout}:{user:User;onLogout:()=>void}){
  const[page,setPage]=useState<PageKey>("dashboard"),[drawer,setDrawer]=useState(false),[collapsed,setCollapsed]=useState(false),[passwordOpen,setPasswordOpen]=useState(false);const screens=Grid.useBreakpoint();
  const items=useMemo(()=>[{key:"dashboard",icon:<AppstoreOutlined/>,label:"Dashboard"},...(user.role==="admin"?[{key:"profiles",icon:<UserOutlined/>,label:"Profiles"},{key:"users",icon:<TeamOutlined/>,label:"Users"}]:[]),{key:"jobs",icon:<ProjectOutlined/>,label:"Job Apply"},{key:"settings",icon:<SettingOutlined/>,label:"Settings"}], [user.role]);
  const menu=<Menu theme="dark" mode="inline" selectedKeys={[page]} items={items} onClick={({key})=>{setPage(key as PageKey);setDrawer(false)}}/>;
  const currentLabel=items.find(item=>item.key===page)?.label;
  return <Layout className="app-layout">{screens.lg?<Layout.Sider width={244} collapsedWidth={80} collapsible collapsed={collapsed} trigger={null} className="app-sider">{menu}</Layout.Sider>:<Drawer open={drawer} onClose={()=>setDrawer(false)} placement="left" width={264} styles={{body:{padding:0}}}>{menu}</Drawer>}<Layout className={`workspace-main ${collapsed&&screens.lg?"workspace-main-collapsed":""}`}><Layout.Header className="app-header"><Button className="custom-sider-trigger" type="text" aria-label={screens.lg?(collapsed?"Expand sidebar":"Collapse sidebar"):"Open navigation"} icon={screens.lg?(collapsed?<MenuUnfoldOutlined/>:<MenuFoldOutlined/>):<MenuUnfoldOutlined/>} onClick={()=>screens.lg?setCollapsed(value=>!value):setDrawer(true)}/><div className="header-page-name">{currentLabel}</div><div className="header-spacer"/><Dropdown menu={{items:[{key:"password",label:"Change password",icon:<KeyOutlined/>,onClick:()=>setPasswordOpen(true)},{type:"divider"},{key:"logout",label:"Sign out",icon:<LogoutOutlined/>,danger:true,onClick:onLogout}]}}><Button type="text" className="user-chip"><Avatar>{user.user_id[0].toUpperCase()}</Avatar><span className="user-chip-copy"><strong>{user.user_id}</strong><small>{user.role}</small></span></Button></Dropdown><ChangePasswordModal open={passwordOpen} onClose={()=>setPasswordOpen(false)}/></Layout.Header><Layout.Content className="app-content"><Suspense fallback={<Skeleton active/>}>{page==="dashboard"&&<DashboardPage user={user}/>} {page==="profiles"&&user.role==="admin"&&<ProfilesPage/>} {page==="users"&&user.role==="admin"&&<UsersPage currentUser={user}/>} {page==="jobs"&&<JobsPage user={user}/>} {page==="settings"&&<SettingsPage/>}</Suspense></Layout.Content></Layout></Layout>;
}

export default function App(){const[user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(Boolean(authStore.get()));useEffect(()=>{if(!authStore.get()){setLoading(false);return}api.me().then(setUser).catch(()=>authStore.clear()).finally(()=>setLoading(false))},[]);return <AntApp>{loading?<div className="boot"><Skeleton active/></div>:user?<Workspace user={user} onLogout={()=>{authStore.clear();setUser(null)}}/>:<SignIn onLogin={setUser}/>}</AntApp>}
